[package]
name = "rust_thread_executor"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_thread_executor"
crate-type = ["cdylib"]

[dependencies.pyo3]
pyo3 = { version = "0.20.3", features = ["extension-module"] }